<?php namespace CventQuery\CallType;

use CventQuery\CventObject\CventObjectInterface;
use stdClass;

/**
 * Created by PhpStorm.
 * User: goce
 * Date: 11/10/15
 * Time: 11:42
 *
 * Responsible for running a SearchCall against cvent's soap apis
 *
 *
 */

class SearchCall extends BaseCall {

  const SEARCH_CALL_NAME = "Search";

  protected $cvSearchObject;

  private $orSearch = 'OrSearch';
  private $andSearch = 'AndSearch';

  /**
   * SearchCall constructor.
   *
   * @param \CventQuery\CventConnection $connection
   * @param                             $data
   */
  public function __construct(\CventQuery\CventConnection $connection, CventObjectInterface $cventObject) {
    parent::__construct($connection, self::SEARCH_CALL_NAME, $cventObject->type());

    $this->cvSearchObject = new stdClass();
    $this->cvSearchObject->SearchType = $this->orSearch;
  }

  public function runQuery() {

    $this->data->CvSearchObject = $this->cvSearchObject;

    return parent::runQuery(); // TODO: Change the autogenerated stub
  }
}